### ISSUE TITLE
Update instructions to add theme to `kitty/themes`

### ISSUE THREAD

**Issue by guzman109** [Biscuit-Colorscheme/kitty#1]
https://sw.kovidgoyal.net/kitty/kittens/themes/#using-your-own-themes

Per this, you can just create a `theme` directory in your `.config/kitty` and it will pick up any custom themes. Just thought you could update the instructions to do so instead of having to modify `kitty.conf`. Plus this way you can use `kitty +kitten themes` to switch the theme at any time.

**Comment by ghost** [comment]
never saw that! i'll look forward to adding it to the installation guide when possible!

thank you for sending me this, btw! (i may suggest Biscuit to the themes repository, but i obviously need approval to do this)
